project: dmae
program: train_dm.py
command:
  - /gpfs/gibbs/pi/krishnaswamy_smita/xingzhi/.conda_envs/geosink/bin/python
  - ${program}
  - ${args_no_hyphens}

method: grid  # or 'random', 'bayes'
metric:
  name: train_loss
  goal: minimize
parameters:
  time_embedding_size: 
    values: [16,32]
  lr: 
    values: [1e-3,1e-4]
  dropout:
    values: [0.2,0.5]
  data:
    # values: ['eb_all_new.npz']
    # values: ['eb_all_new_2.npz']
    values: ['sea_ad_all_new.npz', 'sea_ad_all_new_2.npz']
  layer_widths:
    values: [[64,128,256],[64,64,64]]
  batch_size: 
    values: [1024,256]
num_steps:
  values: [100,1000,10000]