project: dmae
program: train_dm.py
command:
  - /gpfs/gibbs/pi/krishnaswamy_smita/xingzhi/.conda_envs/geosink/bin/python
  - ${program}
  - ${args_no_hyphens}

method: grid  # or 'random','bayes'
metric:
  name: train_loss
  goal: minimize
parameters:
  path: 
    values: ['../data/diffusion_model_neurips_ae/']
  time_embedding_size: 
    values: [16]
  lr: 
    values: [1e-3,1e-4]
  dropout:
    values: [0.]
  weight_decay: 
    values: [1e-5,1e-6]
  batch_norm: 
    values: [false]
  data:
    values: ['EB_phate_2_dm.npz','EB_phate_10_dm.npz','EB_phate_20_dm.npz','EB_phate_30_dm.npz']
    # values: ['eb_subset_all_15_dm.npz']
  layer_widths:
    values: [[64,128,256],[256,256,256]]
  batch_size: 
    values: [1024]
  num_steps:
    # values: [1000,10000,50000]
    values: [2000,5000,20000] 