logger:
  use_wandb: True
  entity: xingzhis
  project: "dmae"
  # tags: ['swiss_roll']
  tags: ['eb_hv_pca', 'subset']

model:
  emb_dim: 2
  log_dist: true
  w: 64
  lr: 1e-3
  activation: 'relu'

data:
  batch_size: 1024
  # file_format: 'h5ad'
  # datapath: '../data/opc.h5ad'
  file_type: 'npy'
  # datapath: '../data/swiss_roll.npy'
  # datapath: '../data/eb_hv_pca.npy'
  datapath: '../data/eb_hv_pca_subset.npy'

training:
  max_epochs: 50
  patience: 10
  monitor: 'val_loss'
  accelerator: 'cuda'
  log_every_n_steps: 10

phate:
  random_state: 42
  knn: 4
  decay: 15
  t: 12
  n_jobs: -2

