data:
  root: 'data'
  filetype: '.npz'
  name: 'splatter' #'tree' #'s_curve' #'swiss_roll' # 'myeloid'
  noise: 0.1
  seed: 1
  preprocess: 'none'
  knn: 5
  t: 0
  noisy_path: 'noisy_44_groups_17580_2000_3_0.4_0.5_all.npz' # Only relevant to splatter
logger:
  entity: danqiliao
  project: dmae
  tags: 'dist'
  use_wandb: true
model:
  activation: relu
  layer_widths:
  - 256
  - 128
  - 64
  dist_reconstr_weights: [0.9, 0.1]
  encoding_method: 'distance' # 'tsne'
  dist_normalization: 'zscore'
  alpha: 1.0
  bandwidth: 1.0
  load_encoder: false
  load_decoder: false
path:
  log: log.txt
  model: model.ckpt
  out_data: ''
  plots: ''
  root: dist_results/
  save: true
training:
  accelerator: auto
  batch_size: 256
  log_every_n_epochs: 5
  max_epochs: 5000
  monitor: val_loss
  patience: 100
  seed: 2024
  shuffle: true
  train_test_split: 0.8
  train_valid_split: 0.8
  lr: 1e-3
  weight_decay: 1e-4


hydra:
  mode: MULTIRUN
  sweeper:
    params:
      ++data.name : swiss_roll
      ++logger.use_wandb: true
      ++data.knn: 40
      ++data.noise: 0.1
      ++data.t: 26