data:
  root: 'data'
  filetype: '.npz'
  name: 'swiss_roll' #'tree' #'s_curve' #'swiss_roll'
  noise: 1.0
  preprocess: 'none'
  knn: 5
logger:
  project: dmae
  tags:
  - probae
  use_wandb: true
model:
  activation: relu
  dist_recon_topk_coords: 0
  dist_reconstr_weights:
  - 1.0
  - 0.0
  - 0
  layer_widths:
  - 256
  - 128
  - 64
  prob_method: 'gaussian'
  alpha: 1.0
  bandwidth: 1.0
path:
  log: ''
  model: model.ckpt
  plots: ''
  root: results/
  save: true
training:
  accelerator: cpu
  batch_size: 256
  log_every_n_steps: 100
  match_potential: false
  max_epochs: 5000
  monitor: val_loss
  patience: 100
  seed: 2024
  shuffle: true
  train_test_split: 0.8
  train_valid_split: 0.8
  lr: 1e-3
  weight_decay: 1e-4
