data:
  root: 'data'
  filetype: '.npz'
  name: 'swiss_roll' #'tree' #'s_curve' #'swiss_roll'
  noise: 1.0
  preprocess: 'none'
  knn: 5
logger:
  entity: danqiliao
  project: dmae
  tags: separate_affinity
  use_wandb: true
model:
  activation: relu
  layer_widths:
  - 256
  - 128
  - 64
  dist_reconstr_weights: [1.0, 0]
  prob_method: 'gaussian'
  alpha: 1.0
  bandwidth: 1.0
  load_encoder: false
  load_decoder: false
path:
  log: log.txt
  model: model.ckpt
  decoder_model: decoder.ckpt
  out_data: ''
  plots: ''
  root: results/
  save: true
training:
  accelerator: cpu
  batch_size: 256
  log_every_n_steps: 100
  max_epochs: 5000
  monitor: val_loss
  patience: 100
  seed: 2024
  shuffle: true
  train_test_split: 0.8
  train_valid_split: 0.8
  lr: 1e-3
  weight_decay: 1e-4
