log_dist: true
layer_widths: [64, 64, 64]
lr: 0.001
weight_decay: 0.0001
dropout: 0.5
batch_norm: true
activation: 'relu'
dist_reconstr_weights: [0.9, 0.1, 0.]
dist_recon_topk_coords: 0
type: 'ae'
kl_weight: 0.1
use_dist_mse_decay: false
dist_mse_decay: 0.1
cycle_weight: 0.
cycle_dist_weight: 0.