dimensions:
  latent: 2
  data: 100

encoder:
  layer_widths: [64,64,64]
  activation: relu
  batch_norm: False
  dropout: 0.0

decoder:
  layer_widths: [64,64,64]
  activation: relu
  batch_norm: False
  dropout: 0.0

training:
  lr: 1e-3
  weight_decay: 1e-4
  batch_size: 256
  monitor: 'validation/loss'
  patience: 50
  accelerator: 'cuda'
  log_every_n_steps: 100
  max_epochs: 50
  train_valid_split: 0.8
  seed: 42
  shuffle: true
  # mode: 'end2end' # separate
  mode: 'separate'

loss:
  dist_mse_decay: 0.
  weights:
    dist: 1
    reconstr: 1
    cycle: 0.
    cycle_dist: 0.

path:
  root: '../results/'
  model: 'model'

data:
  root: '../toy_data/converted'
  filetype: '.npz'
  name: 'make_mix_surface'

logger:
  use_wandb: True
  entity: xingzhis
  project: "dmae"
  tags: ['default']