dimensions:
  latent: 2
  data: 100

encoder:
  layer_widths: [64,64,64]
  activation: relu
  batch_norm: False
  dropout: 0.0
  spectral_norm: False

decoder:
  layer_widths: [64,64,64]
  activation: relu
  batch_norm: False
  dropout: 0.0
  spectral_norm: False

training:
  lr: 1e-3
  weight_decay: 1e-4
  batch_size: 256
  monitor: 'validation/loss'
  patience: 50
  accelerator: 'cuda'
  log_every_n_steps: 100
  max_epochs: 50
  train_valid_split: 0.8
  seed: 42
  shuffle: true
  # mode: 'end2end' # separate
  mode: 'separate'
  clip: False
  clamp: 0.1
  sample_rate: 0.1
  gradient_penalty_frequency: 10

loss:
  dist_mse_decay: 0.
  weights:
    dist: 1
    reconstr: 1
    cycle: 0.
    cycle_dist: 0.
    negative: 0.
    wgan: 1.
    grad: 1.
    pos1: 1.

path:
  root: '../results/'
  model: 'model'
  log: ''

data:
  root: '../toy_data/converted'
  filetype: '.npz'
  name: 'make_mix_surface'

fimm:
  t: 1.
  alpha: 1.
  bandwidth: 1.
  knn: 5
  prob_method: 'gaussian'

logger:
  use_wandb: True
  entity: xingzhis
  project: "dmae"
  tags: ['default']
