project: dmae
program: train.py
command:
  - /gpfs/gibbs/pi/krishnaswamy_smita/xingzhi/.conda_envs/geosink/bin/python
  - ${program}
  - ${args_no_hyphens}
method: grid  # or 'random', 'bayes'
metric:
  name: validation/loss
  goal: minimize
parameters:
  data.root: 
    values: ['../data/neurips_results/toy/disc/']
  data.name:
    # values: ['hemisphere_none_0','hemisphere_5_0','hemisphere_15_0','hemisphere_50_0','hemisphere_15_0.1','hemisphere_15_0.3','swissroll_none_0','swissroll_5_0','swissroll_15_0','swissroll_50_0','swissroll_15_0.1','swissroll_15_0.3','ellipsoid_15_0.1','ellipsoid_15_0','ellipsoid_5_0','ellipsoid_15_0.3','ellipsoid_50_0','ellipsoid_none_0','torus_15_0.1','torus_15_0.3','torus_15_0','torus_50_0','torus_5_0','torus_none_0','saddle_15_0.1','saddle_15_0.3','saddle_15_0','saddle_50_0','saddle_5_0','saddle_none_0']
    # values: ['swissroll_15_0.3','swissroll_15_0','swissroll_15_0.1','swissroll_none_0','swissroll_50_0','swissroll_5_0','hemisphere_5_0']
    values: ['ellipsoid_15_0', 'ellipsoid_15_0.1', 'ellipsoid_15_0.3', 'ellipsoid_15_0.5', 'ellipsoid_15_0.7', 'ellipsoid_none_0.1', 'ellipsoid_5_0.1', 'ellipsoid_10_0.1', 'ellipsoid_15_0.1', 'ellipsoid_50_0.1', 'hemisphere_15_0', 'hemisphere_15_0.1', 'hemisphere_15_0.3', 'hemisphere_15_0.5', 'hemisphere_15_0.7', 'hemisphere_none_0.1', 'hemisphere_5_0.1', 'hemisphere_10_0.1', 'hemisphere_15_0.1', 'hemisphere_50_0.1', 'saddle_15_0', 'saddle_15_0.1', 'saddle_15_0.3', 'saddle_15_0.5', 'saddle_15_0.7', 'saddle_none_0.1', 'saddle_5_0.1', 'saddle_10_0.1', 'saddle_15_0.1', 'saddle_50_0.1', 'torus_15_0', 'torus_15_0.1', 'torus_15_0.3', 'torus_15_0.5', 'torus_15_0.7', 'torus_none_0.1', 'torus_5_0.1', 'torus_10_0.1', 'torus_15_0.1', 'torus_50_0.1']
    # values: ['hemisphere_none_0','hemisphere_5_0','hemisphere_15_0','hemisphere_50_0','hemisphere_15_0.1','hemisphere_15_0.3','swissroll_none_0','swissroll_5_0','swissroll_15_0','swissroll_50_0','swissroll_15_0.1','swissroll_15_0.3','ellipsoid_15_0.1','ellipsoid_15_0','ellipsoid_5_0','ellipsoid_15_0.3','ellipsoid_50_0','ellipsoid_none_0','torus_15_0.1','torus_15_0.3','torus_15_0','torus_50_0','torus_5_0','torus_none_0','saddle_15_0.1','saddle_15_0.3','saddle_15_0','saddle_50_0','saddle_5_0','saddle_none_0']
  encoder.layer_widths: 
    values: [[256,128,64]]
  encoder.batch_norm: 
    values: [true]
  encoder.spectral_norm: 
    values: [true]
  encoder.dropout: 
    values: [0.5]
  training.mode:
    values: ['wdiscriminator']
  training.max_epochs:
    values: [50]
  training.weight_decay:
    values: [1e-4]
  training.clip:
    values: [True]
  training.clamp:
    # values: [0.01,0.05,0.1]
    values: [0.1]
  loss.weights.pos1:
    values: [1.]