project: dmae
program: train.py
command:
  - /gpfs/gibbs/pi/krishnaswamy_smita/xingzhi/.conda_envs/geosink/bin/python
  - ${program}
  - ${args_no_hyphens}
method: grid  # or 'random', 'bayes'
metric:
  name: validation/loss
  goal: minimize
parameters:
  data.root: 
    values: ['../data/fimm/']
  data.name:
    values: ['eb', 'swissroll_none_0']
  dimensions.latent:
    values: [2,3]
  encoder.layer_widths: 
    values: [[256,128,64]]
  encoder.batch_norm: 
    values: [true]
  encoder.dropout: 
    values: [0.5]
  decoder.layer_widths: 
    values: [[64,128,256]]
  decoder.batch_norm:
    values: [true]
  decoder.dropout:
    values: [0.5]
  training.mode:
    values: ['fimm']
  training.max_epochs:
    values: [50]
  training.max_epochs:
    values: [50]
  loss.dist_mse_decay:
    values: [1,2,10]
  loss.weights.dist:
    values: [77.4]
    # values: [0.9]
  loss.weights.reconstr:
    # values: [0.1]
    values: [0.32]
  loss.weights.cycle:
    # values: [0.,1.]
    values: [0.]
  loss.weights.cycle_dist:
    values: [0]
  fimm.prob_method:
    values: ['gaussian', 'heat_kernel', 'sym_gaussian', 'adjusted_gaussian', 'tstudent', 'powered_tstudent']
  