batch_size: 256
max_epochs: 50
patience: 50
monitor: 'val_loss'
accelerator: 'cuda'
log_every_n_steps: 100
match_potential: true
train_test_split: 0.8
train_valid_split: 0.8
shuffle: true
seed: 42
lr: 1e-3